created fast-company
Fomin-Anatolii/React-beginning_1 pull request #1
Opened 2022-07-07 12:32 UTC by Fomin-Anatolii

2022-07-08 10:48 UTC, AndreiSachuk requested changes
Функция генерации фразы требует доработки

2022-07-08 10:48 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +      number !== 0 ? (classes += ` bg-primary`) : (classes += " bg-danger")
number !== 0    можно записать как !number

2022-07-08 10:48 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    return span
подставь число 22 и посмотри на фразу

2022-07-08 10:48 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    return <span className="badge bg-danger fs-2">Никто не тусанёт с тобой сегодня</span>
по хорошему фразу генерить в методе, где ты ее генеришь)
а таблицу выводить с условным рендерингом
но это пока не критично

2022-07-08 13:03 UTC, Fomin-Anatolii commented on my-app/src/components/users.jsx
> +      number !== 0 ? (classes += ` bg-primary`) : (classes += " bg-danger")
!number ? (classes += " bg-danger") : (classes += ` bg-primary`)

2022-07-08 13:28 UTC, Fomin-Anatolii commented on my-app/src/components/users.jsx
> +    return <span className="badge bg-danger fs-2">Никто не тусанёт с тобой сегодня</span>
Эту часть кода я хочу посмотреть в ответе)) проанализировать и потом переделать

2022-07-08 13:34 UTC, Fomin-Anatolii commented on my-app/src/components/users.jsx
> +    return span
if (number % 10 === 2 || number % 10 === 3 || number % 10 === 4) {
      word = `тусанут`
      people = `человека`
    }
    if (number >= 11 && number <= 14) {
      people = `человек`
      word = `тусанёт`
    }

2022-07-08 14:51 UTC, AndreiSachuk requested changes
не верно
смотри внимательно таблицу

2022-07-08 14:51 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    return span
читай внимательно
1
2
5
12
22
32

2022-07-09 13:00 UTC, AndreiSachuk approved these changes

2022-07-09 13:00 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    number > 1 ? (word = "тусанут") : (word = "тусанёт")
тут хочется тернарный оператор

2022-07-09 13:00 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    let span = (
тут конст надо бы

2022-07-09 13:00 UTC, AndreiSachuk commented on my-app/src/components/users.jsx
> +    if ((number >= 11 && number <= 14) || (number % 100 >= 12 && number % 100 <= 14)) {
не самый оптимальный вариант, но имеет право на жизнь)
едем дальше)

2022-07-09 13:02 UTC, merged